name: Orbital Role Sync CI Deploy
on:
  push:
    branches:
      - main
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /opt/orbital_role_sync
          git fetch --all
          git reset --hard origin/main
          npm install --save
          pm2 restart OrbitalRoleSync
